#!/usr/bin/env bash
# Generate strong values for the admin password + session secret + CLI token.
# Print to stdout in `KEY=VALUE` form so you can review, then paste into
# backend/.env. We DO NOT write to .env automatically — you should never
# script-overwrite live secrets without seeing them first.
#
# Usage:
#   ./infra/security/gen-admin-secrets.sh                # print to stdout
#   ./infra/security/gen-admin-secrets.sh >> backend/.env  # append (review first!)

set -euo pipefail

if ! command -v openssl >/dev/null 2>&1; then
  echo "ERROR: openssl not found. Install it first." >&2
  exit 1
fi

# Password: 24 bytes base64 ≈ 32 printable chars, URL-safe (no +/= confusion)
ADMIN_PASSWORD=$(openssl rand -base64 24 | tr '+/' '-_' | tr -d '=')

# Session secret: 32 bytes hex (64 chars) for HMAC-SHA256
ADMIN_SESSION_SECRET=$(openssl rand -hex 32)

# Static CLI bearer token (separate from browser cookie). 32 bytes hex.
# Used by curl/scripts hitting admin-only endpoints; UI does NOT use this.
ADMIN_TOKEN=$(openssl rand -hex 32)

cat <<EOF
# Generated by infra/security/gen-admin-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_SESSION_SECRET=${ADMIN_SESSION_SECRET}
ADMIN_TOKEN=${ADMIN_TOKEN}
EOF
