import { useQuery, useMutation, useQueryClient, keepPreviousData } from '@tanstack/react-query'
import { apiFetch } from './client'

export interface WorkflowSummary {
  id: string
  name: string
  description: string | null
  is_template: boolean
  status: string
  auto_generated: boolean
  generated_for_service_id: string | null
  nodes: any[]
  edges: any[]
  created_at: string
  updated_at: string
}

export type WorkflowFull = WorkflowSummary

export function useWorkflows(opts?: { isTemplate?: boolean; autoGenerated?: boolean }) {
  const qs = new URLSearchParams()
  if (opts?.isTemplate != null) qs.set('is_template', String(opts.isTemplate))
  if (opts?.autoGenerated != null) qs.set('auto_generated', String(opts.autoGenerated))
  const q = qs.toString()
  return useQuery({
    queryKey: ['workflows', opts?.isTemplate ?? null, opts?.autoGenerated ?? null],
    queryFn: () => apiFetch<WorkflowSummary[]>(`/api/v1/workflows${q ? `?${q}` : ''}`),
    placeholderData: keepPreviousData,
    staleTime: 30_000,
  })
}

export function useWorkflow(id: string | null) {
  return useQuery({
    queryKey: ['workflow', id],
    queryFn: () => apiFetch<WorkflowFull>(`/api/v1/workflows/${id}`),
    enabled: !!id,
  })
}

export function useCreateWorkflow() {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (data: { name: string; nodes?: any[]; edges?: any[]; is_template?: boolean }) =>
      apiFetch<WorkflowFull>('/api/v1/workflows', {
        method: 'POST',
        body: JSON.stringify(data),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['workflows'] }),
  })
}

export function useSaveWorkflow() {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: ({ id, ...data }: { id: string; name?: string; nodes?: any[]; edges?: any[] }) =>
      apiFetch<WorkflowFull>(`/api/v1/workflows/${id}`, {
        method: 'PATCH',
        body: JSON.stringify(data),
      }),
    onSuccess: (_, vars) => {
      qc.invalidateQueries({ queryKey: ['workflow', vars.id] })
      qc.invalidateQueries({ queryKey: ['workflows'] })
    },
  })
}

export function useDeleteWorkflow() {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (id: string) =>
      apiFetch(`/api/v1/workflows/${id}`, { method: 'DELETE' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['workflows'] }),
  })
}

export function usePublishWorkflow() {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (id: string) =>
      apiFetch<{ instance_id: string; endpoint: string }>(
        `/api/v1/workflows/${id}/publish`,
        { method: 'POST' }
      ),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['workflows'] })
    },
  })
}

export function useUnpublishWorkflow() {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (id: string) =>
      apiFetch(`/api/v1/workflows/${id}/unpublish`, { method: 'POST' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['workflows'] }),
  })
}
