"""baseline

Revision ID: be779bfc6f87
Revises: 
Create Date: 2026-07-06 15:18:48.810419
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # JSONB(astext_type=Text()) 引用;autogenerate 漏 import 手动补
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be779bfc6f87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_logs_timestamp'), 'app_logs', ['timestamp'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('execution_tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workflow_id', sa.BigInteger(), nullable=True),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('nodes_total', sa.Integer(), nullable=False),
    sa.Column('nodes_done', sa.Integer(), nullable=False),
    sa.Column('current_node', sa.String(length=100), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('gpu_group', sa.String(length=32), nullable=True),
    sa.Column('runner_id', sa.String(length=32), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_timings', sa.JSON(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=200), nullable=True),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_events', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_tasks_created', 'execution_tasks', ['created_at'], unique=False)
    op.create_table('frontend_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('page', sa.String(length=500), nullable=True),
    sa.Column('stack', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frontend_logs_timestamp'), 'frontend_logs', ['timestamp'], unique=False)
    op.create_table('llm_usage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=True),
    sa.Column('api_key_id', sa.BigInteger(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_usage_created', 'llm_usage', ['created_at'], unique=False)
    op.create_index('idx_llm_usage_instance_created', 'llm_usage', ['instance_id', 'created_at'], unique=False)
    op.create_index('idx_llm_usage_model_created', 'llm_usage', ['model', 'created_at'], unique=False)
    op.create_index(op.f('ix_llm_usage_agent_id'), 'llm_usage', ['agent_id'], unique=False)
    op.create_table('model_metadata',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('engine_key', sa.String(length=50), nullable=False),
    sa.Column('modelscope_id', sa.String(length=200), nullable=True),
    sa.Column('hf_id', sa.String(length=200), nullable=True),
    sa.Column('organization', sa.String(length=100), nullable=True),
    sa.Column('model_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('frameworks', sa.JSON(), nullable=True),
    sa.Column('libraries', sa.JSON(), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('tensor_types', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metadata_engine_key'), 'model_metadata', ['engine_key'], unique=True)
    op.create_table('model_runtime_overrides',
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('resident', sa.Boolean(), nullable=True),
    sa.Column('gpu', sa.Integer(), nullable=True),
    sa.Column('vram_budget_mode', sa.String(length=20), nullable=True),
    sa.Column('vram_budget_value', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('request_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_timestamp'), 'request_logs', ['timestamp'], unique=False)
    op.create_table('service_instances',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('source_name', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('meter_dim', sa.String(length=20), nullable=True),
    sa.Column('endpoint_path', sa.String(length=200), nullable=True),
    sa.Column('params_override', sa.JSON(), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('rate_limit_tpm', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.BigInteger(), nullable=True),
    sa.Column('workflow_snapshot', sa.JSON(), nullable=False),
    sa.Column('exposed_inputs', sa.JSON(), nullable=False),
    sa.Column('exposed_outputs', sa.JSON(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=80), nullable=True),
    sa.Column('snapshot_schema_version', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_service_snapshot_hash', 'service_instances', ['snapshot_hash'], unique=False)
    op.create_index('ix_service_instances_source', 'service_instances', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_service_instances_source_id'), 'service_instances', ['source_id'], unique=False)
    op.create_table('status_samples',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('component', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status_component_ts', 'status_samples', ['component', 'ts'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('totp_secrets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tts_usage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.Column('characters', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('rtf', sa.Float(), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tts_usage_created', 'tts_usage', ['created_at'], unique=False)
    op.create_index('idx_tts_usage_engine', 'tts_usage', ['engine'], unique=False)
    op.create_table('voice_preset_groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('presets', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('voice_presets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('reference_audio_path', sa.String(length=500), nullable=True),
    sa.Column('reference_text', sa.String(length=1000), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('webauthn_credentials',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.BigInteger(), nullable=False),
    sa.Column('transports', sa.String(length=200), nullable=True),
    sa.Column('aaguid', sa.LargeBinary(), nullable=True),
    sa.Column('backup_eligible', sa.Boolean(), nullable=False),
    sa.Column('backup_state', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webauthn_credentials_credential_id'), 'webauthn_credentials', ['credential_id'], unique=True)
    op.create_table('context_caches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('api_key_id', sa.BigInteger(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('messages_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('ttl_seconds >= 60 AND ttl_seconds <= 604800', name='context_cache_ttl_range'),
    sa.ForeignKeyConstraint(['instance_id'], ['service_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_context_caches_expires_at', 'context_caches', ['expires_at'], unique=False)
    op.create_index('ix_context_caches_instance_expires', 'context_caches', ['instance_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_context_caches_instance_id'), 'context_caches', ['instance_id'], unique=False)
    op.create_table('instance_api_keys',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=200), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('secret_plaintext', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_calls', sa.Integer(), nullable=False),
    sa.Column('usage_chars', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['service_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instance_api_keys_expires_at'), 'instance_api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_instance_api_keys_instance_id'), 'instance_api_keys', ['instance_id'], unique=False)
    op.create_index(op.f('ix_instance_api_keys_key_prefix'), 'instance_api_keys', ['key_prefix'], unique=False)
    op.create_table('memory_entries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=True),
    sa.Column('api_key_id', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['service_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mem_key_created', 'memory_entries', ['api_key_id', 'created_at'], unique=False)
    op.create_index('idx_mem_key_ctx_cat', 'memory_entries', ['api_key_id', 'context_key', 'category'], unique=False)
    op.create_index(op.f('ix_memory_entries_api_key_id'), 'memory_entries', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_memory_entries_instance_id'), 'memory_entries', ['instance_id'], unique=False)
    op.create_table('response_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('api_key_id', sa.BigInteger(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('context_cache_id', sa.String(length=64), nullable=True),
    sa.Column('total_input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expire_at > created_at', name='response_session_expire_at_check'),
    sa.ForeignKeyConstraint(['instance_id'], ['service_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_sessions_agent_id'), 'response_sessions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_response_sessions_expire_at'), 'response_sessions', ['expire_at'], unique=False)
    op.create_index('ix_response_sessions_instance_created', 'response_sessions', ['instance_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_response_sessions_instance_id'), 'response_sessions', ['instance_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.Column('groups', sa.JSON(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('generated_for_service_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_for_service_id'], ['service_instances.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_key_grants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('api_key_id', sa.BigInteger(), nullable=False),
    sa.Column('service_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['instance_api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'service_id', name='uq_grant_key_service')
    )
    op.create_index(op.f('ix_api_key_grants_api_key_id'), 'api_key_grants', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_api_key_grants_service_id'), 'api_key_grants', ['service_id'], unique=False)
    op.create_index('ix_grant_active', 'api_key_grants', ['api_key_id', 'status'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('api_key_id', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['instance_api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'sha256', name='uq_files_apikey_sha256')
    )
    op.create_index(op.f('ix_files_api_key_id'), 'files', ['api_key_id'], unique=False)
    op.create_index('ix_files_apikey_created', 'files', ['api_key_id', 'created_at'], unique=False)
    op.create_table('memory_embeddings',
    sa.Column('entry_id', sa.BigInteger(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['memory_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('response_turns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('turn_idx', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content_compressed', sa.LargeBinary(), nullable=False),
    sa.Column('usage_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('reasoning_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('text_format', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('incomplete_reason', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['response_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'turn_idx', name='uq_response_turn_session_idx')
    )
    op.create_index(op.f('ix_response_turns_session_id'), 'response_turns', ['session_id'], unique=False)
    op.create_index('ix_response_turns_session_idx', 'response_turns', ['session_id', 'turn_idx'], unique=False)
    op.create_table('resource_packs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('grant_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('total_units', sa.BigInteger(), nullable=False),
    sa.Column('used_units', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['api_key_grants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pack_grant_active', 'resource_packs', ['grant_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_resource_packs_expires_at'), 'resource_packs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_resource_packs_grant_id'), 'resource_packs', ['grant_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('grant_id', sa.BigInteger(), nullable=False),
    sa.Column('threshold_percent', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.BigInteger(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['api_key_grants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pack_id'], ['resource_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_grant_enabled', 'alert_rules', ['grant_id', 'enabled'], unique=False)
    op.create_index(op.f('ix_alert_rules_grant_id'), 'alert_rules', ['grant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_rules_grant_id'), table_name='alert_rules')
    op.drop_index('ix_alert_grant_enabled', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_resource_packs_grant_id'), table_name='resource_packs')
    op.drop_index(op.f('ix_resource_packs_expires_at'), table_name='resource_packs')
    op.drop_index('ix_pack_grant_active', table_name='resource_packs')
    op.drop_table('resource_packs')
    op.drop_index('ix_response_turns_session_idx', table_name='response_turns')
    op.drop_index(op.f('ix_response_turns_session_id'), table_name='response_turns')
    op.drop_table('response_turns')
    op.drop_table('memory_embeddings')
    op.drop_index('ix_files_apikey_created', table_name='files')
    op.drop_index(op.f('ix_files_api_key_id'), table_name='files')
    op.drop_table('files')
    op.drop_index('ix_grant_active', table_name='api_key_grants')
    op.drop_index(op.f('ix_api_key_grants_service_id'), table_name='api_key_grants')
    op.drop_index(op.f('ix_api_key_grants_api_key_id'), table_name='api_key_grants')
    op.drop_table('api_key_grants')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_response_sessions_instance_id'), table_name='response_sessions')
    op.drop_index('ix_response_sessions_instance_created', table_name='response_sessions')
    op.drop_index(op.f('ix_response_sessions_expire_at'), table_name='response_sessions')
    op.drop_index(op.f('ix_response_sessions_agent_id'), table_name='response_sessions')
    op.drop_table('response_sessions')
    op.drop_index(op.f('ix_memory_entries_instance_id'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_api_key_id'), table_name='memory_entries')
    op.drop_index('idx_mem_key_ctx_cat', table_name='memory_entries')
    op.drop_index('idx_mem_key_created', table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_index(op.f('ix_instance_api_keys_key_prefix'), table_name='instance_api_keys')
    op.drop_index(op.f('ix_instance_api_keys_instance_id'), table_name='instance_api_keys')
    op.drop_index(op.f('ix_instance_api_keys_expires_at'), table_name='instance_api_keys')
    op.drop_table('instance_api_keys')
    op.drop_index(op.f('ix_context_caches_instance_id'), table_name='context_caches')
    op.drop_index('ix_context_caches_instance_expires', table_name='context_caches')
    op.drop_index('ix_context_caches_expires_at', table_name='context_caches')
    op.drop_table('context_caches')
    op.drop_index(op.f('ix_webauthn_credentials_credential_id'), table_name='webauthn_credentials')
    op.drop_table('webauthn_credentials')
    op.drop_table('voice_presets')
    op.drop_table('voice_preset_groups')
    op.drop_index('idx_tts_usage_engine', table_name='tts_usage')
    op.drop_index('idx_tts_usage_created', table_name='tts_usage')
    op.drop_table('tts_usage')
    op.drop_table('totp_secrets')
    op.drop_table('tasks')
    op.drop_index('idx_status_component_ts', table_name='status_samples')
    op.drop_table('status_samples')
    op.drop_index(op.f('ix_service_instances_source_id'), table_name='service_instances')
    op.drop_index('ix_service_instances_source', table_name='service_instances')
    op.drop_index('idx_service_snapshot_hash', table_name='service_instances')
    op.drop_table('service_instances')
    op.drop_index(op.f('ix_request_logs_timestamp'), table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_table('model_runtime_overrides')
    op.drop_index(op.f('ix_model_metadata_engine_key'), table_name='model_metadata')
    op.drop_table('model_metadata')
    op.drop_index(op.f('ix_llm_usage_agent_id'), table_name='llm_usage')
    op.drop_index('idx_llm_usage_model_created', table_name='llm_usage')
    op.drop_index('idx_llm_usage_instance_created', table_name='llm_usage')
    op.drop_index('idx_llm_usage_created', table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index(op.f('ix_frontend_logs_timestamp'), table_name='frontend_logs')
    op.drop_table('frontend_logs')
    op.drop_index('ix_execution_tasks_created', table_name='execution_tasks')
    op.drop_table('execution_tasks')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_app_logs_timestamp'), table_name='app_logs')
    op.drop_table('app_logs')
    # ### end Alembic commands ###
