"""add execution_tasks.api_key_id

Revision ID: 91fbe4eca0b3
Revises: be779bfc6f87
Create Date: 2026-07-06 20:57:45.737234
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91fbe4eca0b3'
down_revision: Union[str, None] = 'be779bfc6f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_tasks', sa.Column('api_key_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_tasks', 'api_key_id')
    # ### end Alembic commands ###
