import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Plus, Search } from 'lucide-react'
import { useWorkflows, useCreateWorkflow, type WorkflowSummary } from '../api/workflows'
// (legacy duplicate import removed below)
import { useServices, type ServiceRow } from '../api/services'

type Tab = 'all' | 'mine' | 'template' | 'published'

const TABS: { id: Tab; label: string }[] = [
  { id: 'all', label: '全部' },
  { id: 'mine', label: '我的' },
  { id: 'template', label: '模板' },
  { id: 'published', label: '已发布' },
]

export default function WorkflowsList() {
  // Hide auto-generated trivial workflows by default; the m08 page is for
  // hand-built DAGs.
  const { data: workflows, isLoading, error } = useWorkflows({ autoGenerated: false })
  const { data: services } = useServices()
  const navigate = useNavigate()
  const [tab, setTab] = useState<Tab>('all')
  const [search, setSearch] = useState('')

  const create = useCreateWorkflowAndGo()

  // Group services by source workflow id so each card can show its
  // associated service link without an extra round-trip per row.
  const servicesByWorkflow = useMemo(() => indexServicesByWorkflow(services ?? []), [services])
  const counts = useMemo(() => buildCounts(workflows ?? []), [workflows])
  const filtered = useMemo(
    () => filter(workflows ?? [], tab, search),
    [workflows, tab, search],
  )

  return (
    <div
      style={{
        position: 'absolute',
        inset: 0,
        overflow: 'auto',
        background: 'var(--bg)',
      }}
    >
      <div style={{ maxWidth: 1200, margin: '0 auto', padding: 20 }}>
        <div style={{ display: 'flex', alignItems: 'flex-start', marginBottom: 14 }}>
          <div style={{ flex: 1 }}>
            <h1 style={{ fontSize: 20, color: 'var(--text)', fontWeight: 600 }}>Workflow</h1>
            <p style={{ fontSize: 13, color: 'var(--muted)', marginTop: 4 }}>
              搭建节点化工作流 · 发布为「服务」后对外暴露 API 端点，通过 API Key 调用
            </p>
          </div>
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            <div style={{ position: 'relative' }}>
              <Search
                size={14}
                style={{
                  position: 'absolute',
                  left: 8,
                  top: '50%',
                  transform: 'translateY(-50%)',
                  color: 'var(--muted)',
                }}
              />
              <input
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="搜索 workflow..."
                style={{
                  width: 220,
                  background: 'var(--bg-accent)',
                  color: 'var(--text)',
                  border: '1px solid var(--border)',
                  borderRadius: 4,
                  padding: '7px 9px 7px 28px',
                  fontSize: 12,
                }}
              />
            </div>
            <button
              type="button"
              onClick={() => create.mutate()}
              disabled={create.isPending}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 4,
                padding: '7px 12px',
                background: 'var(--accent)',
                color: '#fff',
                border: 'none',
                borderRadius: 4,
                fontSize: 12,
                cursor: create.isPending ? 'wait' : 'pointer',
                opacity: create.isPending ? 0.6 : 1,
              }}
            >
              <Plus size={14} />
              新建
            </button>
          </div>
        </div>

        <div style={{ display: 'flex', gap: 4, marginBottom: 14 }}>
          {TABS.map((t) => {
            const n = counts[t.id]
            const active = tab === t.id
            return (
              <button
                key={t.id}
                type="button"
                onClick={() => setTab(t.id)}
                style={{
                  padding: '6px 12px',
                  background: active
                    ? 'var(--accent-subtle, rgba(99,102,241,0.1))'
                    : 'transparent',
                  color: active ? 'var(--accent)' : 'var(--muted)',
                  border: '1px solid',
                  borderColor: active ? 'var(--accent)' : 'var(--border)',
                  borderRadius: 4,
                  fontSize: 12,
                  cursor: 'pointer',
                }}
              >
                {t.label} {n}
              </button>
            )
          })}
        </div>

        {isLoading && <Loading />}
        {error && <ErrorBlock message={(error as Error).message} />}
        {workflows && workflows.length === 0 && (
          <Empty onCreate={() => create.mutate()} />
        )}

        {filtered && filtered.length > 0 && (
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))',
              gap: 12,
            }}
          >
            {filtered.map((wf) => (
              <WorkflowCard
                key={wf.id}
                wf={wf}
                service={servicesByWorkflow.get(String(wf.id)) ?? null}
                onOpen={() => navigate(`/workflows/${wf.id}`)}
                onDetail={(svcId) => navigate(`/services/${svcId}`)}
              />
            ))}
            <NewWorkflowCard onClick={() => create.mutate()} />
          </div>
        )}
      </div>
    </div>
  )
}

// ---------- card ----------

function WorkflowCard({
  wf,
  service,
  onOpen,
  onDetail,
}: {
  wf: WorkflowSummary
  service: ServiceRow | null
  onOpen: () => void
  onDetail: (serviceId: string) => void
}) {
  const nodeCount = wf.nodes?.length ?? 0
  const isPublished = wf.status === 'published' || !!service
  const isTemplate = wf.is_template
  return (
    <div
      style={{
        background: 'var(--bg-accent)',
        border: '1px solid var(--border)',
        borderRadius: 8,
        padding: 14,
        display: 'flex',
        flexDirection: 'column',
        gap: 10,
      }}
    >
      <button
        type="button"
        onClick={onOpen}
        style={{
          textAlign: 'left',
          background: 'transparent',
          border: 'none',
          padding: 0,
          cursor: 'pointer',
          color: 'var(--text)',
        }}
      >
        <ThumbStrip count={nodeCount} />
        <div
          style={{
            display: 'flex',
            alignItems: 'baseline',
            gap: 6,
            marginBottom: 4,
          }}
        >
          <span style={{ fontSize: 13, color: 'var(--text)', fontWeight: 500 }}>
            {wf.name}
          </span>
          {/* m08 mockup 对齐：每张卡显示短 ID（末 6 位），方便和服务卡片
              "来自 {name} #xxxxxx" 互查。完整 ID hover title 看。 */}
          <span
            title={`workflow_id=${wf.id}`}
            style={{
              fontSize: 10,
              fontFamily: 'var(--mono, monospace)',
              color: 'var(--muted)',
            }}
          >
            #{shortWfId(String(wf.id))}
          </span>
        </div>
        <div
          style={{
            fontSize: 11,
            color: 'var(--muted)',
            display: 'flex',
            gap: 8,
            alignItems: 'center',
          }}
        >
          {isTemplate ? (
            <Badge color="purple">模板</Badge>
          ) : isPublished ? (
            <Badge color="green">已发布</Badge>
          ) : (
            <Badge>未发布</Badge>
          )}
          <span>
            {nodeCount} 节点
            {wf.status === 'draft' && ' · 编辑中'}
          </span>
        </div>
      </button>

      {!isTemplate && (
        <div
          style={{
            marginTop: 6,
            paddingTop: 10,
            borderTop: '1px dashed var(--border)',
            display: 'flex',
            gap: 6,
            alignItems: 'center',
          }}
        >
          {service ? (
            <>
              <span
                style={{
                  flex: 1,
                  fontSize: 11,
                  color: 'var(--muted)',
                  overflow: 'hidden',
                  textOverflow: 'ellipsis',
                  whiteSpace: 'nowrap',
                }}
              >
                服务：
                <button
                  type="button"
                  onClick={() => onDetail(service.id)}
                  style={{
                    background: 'transparent',
                    border: 'none',
                    color: 'var(--accent-2, #22c55e)',
                    fontFamily: 'var(--mono, monospace)',
                    cursor: 'pointer',
                    padding: 0,
                  }}
                >
                  {service.name}
                </button>
                <span style={{ color: 'var(--muted)', fontSize: 10, marginLeft: 4 }}>
                  v{service.version}
                </span>
              </span>
              <button
                type="button"
                onClick={onOpen}
                title="再次发布"
                style={{
                  padding: '3px 8px',
                  fontSize: 11,
                  color: 'var(--muted)',
                  background: 'var(--bg)',
                  border: '1px solid var(--border)',
                  borderRadius: 3,
                  cursor: 'pointer',
                }}
              >
                ↻ v{service.version + 1}
              </button>
            </>
          ) : (
            <>
              <span
                style={{
                  flex: 1,
                  fontSize: 11,
                  color: 'var(--muted)',
                }}
              >
                未发布为服务
              </span>
              <button
                type="button"
                onClick={onOpen}
                style={{
                  padding: '3px 8px',
                  fontSize: 11,
                  color: 'var(--accent)',
                  background: 'var(--accent-subtle, rgba(99,102,241,0.1))',
                  border: '1px solid var(--accent-subtle, rgba(99,102,241,0.2))',
                  borderRadius: 3,
                  cursor: 'pointer',
                }}
              >
                发布为服务
              </button>
            </>
          )}
        </div>
      )}
    </div>
  )
}

function NewWorkflowCard({ onClick }: { onClick: () => void }) {
  return (
    <button
      type="button"
      onClick={onClick}
      style={{
        background: 'transparent',
        border: '1px dashed var(--border)',
        borderRadius: 8,
        minHeight: 180,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        color: 'var(--muted)',
        fontSize: 13,
        cursor: 'pointer',
        transition: 'border-color 0.15s, color 0.15s',
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.borderColor = 'var(--accent)'
        e.currentTarget.style.color = 'var(--accent)'
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.borderColor = 'var(--border)'
        e.currentTarget.style.color = 'var(--muted)'
      }}
    >
      <Plus size={18} />
      新建 Workflow
    </button>
  )
}

function ThumbStrip({ count }: { count: number }) {
  // Cheap visual: small bars indicating node count, capped at 5.
  const bars = Math.min(count, 5)
  return (
    <div
      style={{
        height: 60,
        background: 'var(--bg)',
        border: '1px solid var(--border)',
        borderRadius: 4,
        marginBottom: 10,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        padding: 12,
      }}
    >
      {bars === 0 ? (
        <span style={{ color: 'var(--muted)', fontSize: 11 }}>空 workflow</span>
      ) : (
        Array.from({ length: bars }).map((_, i) => (
          <div
            key={i}
            style={{
              width: 36,
              height: 18,
              background: 'var(--bg-elevated, var(--bg-accent))',
              border: '1px solid var(--border)',
              borderRadius: 3,
              fontSize: 9,
              color: 'var(--muted)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            n{i + 1}
          </div>
        ))
      )}
    </div>
  )
}

function Badge({
  color,
  children,
}: {
  color?: 'green' | 'purple'
  children: React.ReactNode
}) {
  const styles =
    color === 'green'
      ? { background: 'rgba(34,197,94,0.15)', color: 'var(--accent-2, #22c55e)' }
      : color === 'purple'
        ? { background: 'rgba(168,85,247,0.15)', color: 'var(--purple, #a855f7)' }
        : { background: 'var(--bg)', color: 'var(--muted)', border: '1px solid var(--border)' }
  return (
    <span style={{ fontSize: 10, padding: '1px 7px', borderRadius: 10, ...styles }}>
      {children}
    </span>
  )
}

// ---------- helpers ----------

function shortWfId(id: string): string {
  return id.length > 6 ? id.slice(-6) : id
}

function indexServicesByWorkflow(rows: ServiceRow[]): Map<string, ServiceRow> {
  const map = new Map<string, ServiceRow>()
  // Latest published version wins (services are sorted by created_at desc).
  for (const r of rows) {
    if (r.source_type !== 'workflow' || !r.workflow_id) continue
    const k = String(r.workflow_id)
    if (!map.has(k)) map.set(k, r)
  }
  return map
}

function buildCounts(rows: WorkflowSummary[]): Record<Tab, number> {
  return {
    all: rows.length,
    mine: rows.filter((r) => !r.is_template).length,
    template: rows.filter((r) => r.is_template).length,
    published: rows.filter((r) => r.status === 'published').length,
  }
}

function filter(rows: WorkflowSummary[], tab: Tab, search: string): WorkflowSummary[] {
  const q = search.trim().toLowerCase()
  return rows.filter((r) => {
    if (tab === 'mine' && r.is_template) return false
    if (tab === 'template' && !r.is_template) return false
    if (tab === 'published' && r.status !== 'published') return false
    if (q && !r.name.toLowerCase().includes(q)) return false
    return true
  })
}

// ---------- create + navigate ----------

function useCreateWorkflowAndGo() {
  const create = useCreateWorkflow()
  const navigate = useNavigate()
  return {
    isPending: create.isPending,
    mutate: () =>
      create.mutate(
        { name: '新工作流' },
        {
          onSuccess: (wf) => navigate(`/workflows/${wf.id}`),
        },
      ),
  }
}

// ---------- bits ----------

function Loading() {
  return (
    <div style={{ textAlign: 'center', padding: 40, color: 'var(--muted)', fontSize: 13 }}>
      加载中…
    </div>
  )
}

function ErrorBlock({ message }: { message: string }) {
  return (
    <div
      style={{
        background: 'rgba(239,68,68,0.1)',
        border: '1px solid var(--error, #ef4444)',
        color: 'var(--error, #ef4444)',
        padding: 14,
        borderRadius: 6,
        fontSize: 13,
      }}
    >
      {message}
    </div>
  )
}

function Empty({ onCreate }: { onCreate: () => void }) {
  return (
    <div
      style={{
        textAlign: 'center',
        padding: 40,
        background: 'var(--bg-accent)',
        border: '1px dashed var(--border)',
        borderRadius: 8,
        color: 'var(--muted)',
      }}
    >
      <div style={{ fontSize: 14, marginBottom: 6 }}>还没有 workflow</div>
      <div style={{ fontSize: 12, marginBottom: 12 }}>
        新建一个画布，搭出 DAG 后点"发布为服务"对外提供 API。
      </div>
      <button
        type="button"
        onClick={onCreate}
        style={{
          padding: '7px 14px',
          background: 'var(--accent)',
          color: '#fff',
          border: 'none',
          borderRadius: 4,
          fontSize: 12,
          cursor: 'pointer',
        }}
      >
        新建 Workflow
      </button>
    </div>
  )
}
