models:
  cosyvoice2:
    gpu: 1
    hf_id: FunAudioLLM/CosyVoice2-0.5B
    local_path: tts/cosyvoice2-0.5b
    modelscope_id: iic/CosyVoice2-0.5B
    name: CosyVoice2-0.5B
    resident: false
    type: tts
    vram_gb: 3
  indextts2:
    gpu: 1
    hf_id: IndexTeam/IndexTTS-2
    local_path: tts/indextts-2
    modelscope_id: IndexTeam/IndexTTS-2
    name: IndexTTS-2
    resident: false
    type: tts
    vram_gb: 4
  moss_tts:
    gpu: 1
    hf_id: openmoss/MOSS-TTS
    local_path: tts/moss-tts
    modelscope_id: openmoss/MOSS-TTS
    name: MOSS-TTS
    resident: false
    type: tts
    vram_gb: 8
  qwen25_vl:
    engine: vllm
    gpu: 1
    hf_id: Qwen/Qwen2.5-VL-7B-Instruct
    modelscope_id: Qwen/Qwen2.5-VL-7B-Instruct
    name: Qwen/Qwen2.5-VL-7B-Instruct
    resident: false
    type: understand
    vram_gb: 16
  qwen3_tts_base:
    gpu: 0
    hf_id: Qwen/Qwen3-TTS-12Hz-1.7B-Base
    local_path: tts/qwen3-tts-1.7b-base
    modelscope_id: Qwen/Qwen3-TTS-12Hz-1.7B-Base
    name: Qwen3-TTS-12Hz-1.7B-Base
    resident: true
    ttl_seconds: 0
    type: tts
    vram_gb: 4
  qwen3_tts_customvoice:
    gpu: 1
    hf_id: Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice
    local_path: tts/qwen3-tts-1.7b-customvoice
    modelscope_id: Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice
    name: Qwen3-TTS-12Hz-1.7B-CustomVoice
    resident: false
    type: tts
    vram_gb: 4
  qwen3_tts_voicedesign:
    gpu: 1
    hf_id: Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign
    local_path: tts/qwen3-tts-1.7b-voicedesign
    modelscope_id: Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign
    name: Qwen3-TTS-12Hz-1.7B-VoiceDesign
    resident: false
    type: tts
    vram_gb: 4
  sdxl:
    gpu: 0
    hf_id: stabilityai/stable-diffusion-xl-base-1.0
    modelscope_id: AI-ModelScope/stable-diffusion-xl-base-1.0
    name: stabilityai/stable-diffusion-xl-base-1.0
    resident: false
    type: image
    vram_gb: 10
  wan21:
    exclusive: true
    gpu:
    - 0
    - 1
    hf_id: Wan-AI/Wan2.1-T2V-14B
    modelscope_id: Wan-AI/Wan2.1-T2V-14B
    name: Wan2.1
    resident: false
    type: video
    vram_gb: 40
